version: '3.4'

services:
  baza:
    image: "postgres"
    restart: always
    environment:
        - POSTGRES_PASSWORD=abc
    volumes:
       - dbVol:/var/lib/postgresql/data
    expose:
        - "5432"
    ports:
        - "5432:5432"
  identity50.server:
    image: ${DOCKER_REGISTRY-}identity50server
    restart: always
    depends_on:
       - baza
    build:
      context: .
      dockerfile: 50Identity/Server/Dockerfile
volumes:
   dbVol: